[package]
name = "statusbar"
version = "1.0.0"
authors = ["Luis Galan <luis.sebastian.galan@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = "0.9"
chrono = "0.4"
sys-info = "0.9"

